/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DBKeynote } from "./DBKeynote";
import { DBKeynoteFromJSON, DBKeynoteFromJSONTyped, DBKeynoteToJSON, DBKeynoteToJSONTyped } from "./DBKeynote";

/**
 *
 * @export
 * @interface DBUser
 */
export interface DBUser {
  /**
   *
   * @type {number}
   * @memberof DBUser
   */
  id?: number;
  /**
   *
   * @type {Array<DBKeynote>}
   * @memberof DBUser
   */
  keynotes?: Array<DBKeynote> | null;
}

/**
 * Check if a given object implements the DBUser interface.
 */
export function instanceOfDBUser(value: object): value is DBUser {
  return true;
}

export function DBUserFromJSON(json: any): DBUser {
  return DBUserFromJSONTyped(json, false);
}

export function DBUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): DBUser {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    keynotes: json["keynotes"] == null ? undefined : (json["keynotes"] as Array<any>).map(DBKeynoteFromJSON),
  };
}

export function DBUserToJSON(json: any): DBUser {
  return DBUserToJSONTyped(json, false);
}

export function DBUserToJSONTyped(value?: DBUser | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    keynotes: value["keynotes"] == null ? undefined : (value["keynotes"] as Array<any>).map(DBKeynoteToJSON),
  };
}
