/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { EnumsResponse } from "./EnumsResponse";
import { EnumsResponseFromJSON, EnumsResponseFromJSONTyped, EnumsResponseToJSON, EnumsResponseToJSONTyped } from "./EnumsResponse";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface EnumsResponseResponseWrapper
 */
export interface EnumsResponseResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof EnumsResponseResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof EnumsResponseResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {EnumsResponse}
   * @memberof EnumsResponseResponseWrapper
   */
  response?: EnumsResponse;
}

/**
 * Check if a given object implements the EnumsResponseResponseWrapper interface.
 */
export function instanceOfEnumsResponseResponseWrapper(value: object): value is EnumsResponseResponseWrapper {
  return true;
}

export function EnumsResponseResponseWrapperFromJSON(json: any): EnumsResponseResponseWrapper {
  return EnumsResponseResponseWrapperFromJSONTyped(json, false);
}

export function EnumsResponseResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumsResponseResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : EnumsResponseFromJSON(json["response"]),
  };
}

export function EnumsResponseResponseWrapperToJSON(json: any): EnumsResponseResponseWrapper {
  return EnumsResponseResponseWrapperToJSONTyped(json, false);
}

export function EnumsResponseResponseWrapperToJSONTyped(value?: EnumsResponseResponseWrapper | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: EnumsResponseToJSON(value["response"]),
  };
}
