/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { KeynoteTransitionType } from "./KeynoteTransitionType";
import {
  KeynoteTransitionTypeFromJSON,
  KeynoteTransitionTypeFromJSONTyped,
  KeynoteTransitionTypeToJSON,
  KeynoteTransitionTypeToJSONTyped,
} from "./KeynoteTransitionType";
import type { KeynoteType } from "./KeynoteType";
import { KeynoteTypeFromJSON, KeynoteTypeFromJSONTyped, KeynoteTypeToJSON, KeynoteTypeToJSONTyped } from "./KeynoteType";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface EnumsResponse
 */
export interface EnumsResponse {
  /**
   *
   * @type {AuthFailureReasons}
   * @memberof EnumsResponse
   */
  authFailureReasons?: AuthFailureReasons;
  /**
   *
   * @type {WrResponseStatus}
   * @memberof EnumsResponse
   */
  wrResponseStatus?: WrResponseStatus;
  /**
   *
   * @type {KeynoteTransitionType}
   * @memberof EnumsResponse
   */
  keynoteTransitionType?: KeynoteTransitionType;
  /**
   *
   * @type {KeynoteType}
   * @memberof EnumsResponse
   */
  keynoteType?: KeynoteType;
}

/**
 * Check if a given object implements the EnumsResponse interface.
 */
export function instanceOfEnumsResponse(value: object): value is EnumsResponse {
  return true;
}

export function EnumsResponseFromJSON(json: any): EnumsResponse {
  return EnumsResponseFromJSONTyped(json, false);
}

export function EnumsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumsResponse {
  if (json == null) {
    return json;
  }
  return {
    authFailureReasons: json["authFailureReasons"] == null ? undefined : AuthFailureReasonsFromJSON(json["authFailureReasons"]),
    wrResponseStatus: json["wrResponseStatus"] == null ? undefined : WrResponseStatusFromJSON(json["wrResponseStatus"]),
    keynoteTransitionType: json["keynoteTransitionType"] == null ? undefined : KeynoteTransitionTypeFromJSON(json["keynoteTransitionType"]),
    keynoteType: json["keynoteType"] == null ? undefined : KeynoteTypeFromJSON(json["keynoteType"]),
  };
}

export function EnumsResponseToJSON(json: any): EnumsResponse {
  return EnumsResponseToJSONTyped(json, false);
}

export function EnumsResponseToJSONTyped(value?: EnumsResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    authFailureReasons: AuthFailureReasonsToJSON(value["authFailureReasons"]),
    wrResponseStatus: WrResponseStatusToJSON(value["wrResponseStatus"]),
    keynoteTransitionType: KeynoteTransitionTypeToJSON(value["keynoteTransitionType"]),
    keynoteType: KeynoteTypeToJSON(value["keynoteType"]),
  };
}
