/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KeynoteDTO } from './KeynoteDTO';
import {
    KeynoteDTOFromJSON,
    KeynoteDTOFromJSONTyped,
    KeynoteDTOToJSON,
    KeynoteDTOToJSONTyped,
} from './KeynoteDTO';
import type { CreateKeynoteDTO } from './CreateKeynoteDTO';
import {
    CreateKeynoteDTOFromJSON,
    CreateKeynoteDTOFromJSONTyped,
    CreateKeynoteDTOToJSON,
    CreateKeynoteDTOToJSONTyped,
} from './CreateKeynoteDTO';
import type { KeynoteUserDTO } from './KeynoteUserDTO';
import {
    KeynoteUserDTOFromJSON,
    KeynoteUserDTOFromJSONTyped,
    KeynoteUserDTOToJSON,
    KeynoteUserDTOToJSONTyped,
} from './KeynoteUserDTO';

/**
 * 
 * @export
 * @interface KeynoteDtosResponse
 */
export interface KeynoteDtosResponse {
    /**
     * 
     * @type {KeynoteDTO}
     * @memberof KeynoteDtosResponse
     */
    keynote?: KeynoteDTO;
    /**
     * 
     * @type {CreateKeynoteDTO}
     * @memberof KeynoteDtosResponse
     */
    createKeynote?: CreateKeynoteDTO;
    /**
     * 
     * @type {KeynoteUserDTO}
     * @memberof KeynoteDtosResponse
     */
    keynoteUser?: KeynoteUserDTO;
}

/**
 * Check if a given object implements the KeynoteDtosResponse interface.
 */
export function instanceOfKeynoteDtosResponse(value: object): value is KeynoteDtosResponse {
    return true;
}

export function KeynoteDtosResponseFromJSON(json: any): KeynoteDtosResponse {
    return KeynoteDtosResponseFromJSONTyped(json, false);
}

export function KeynoteDtosResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeynoteDtosResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'keynote': json['keynote'] == null ? undefined : KeynoteDTOFromJSON(json['keynote']),
        'createKeynote': json['createKeynote'] == null ? undefined : CreateKeynoteDTOFromJSON(json['createKeynote']),
        'keynoteUser': json['keynoteUser'] == null ? undefined : KeynoteUserDTOFromJSON(json['keynoteUser']),
    };
}

export function KeynoteDtosResponseToJSON(json: any): KeynoteDtosResponse {
    return KeynoteDtosResponseToJSONTyped(json, false);
}

export function KeynoteDtosResponseToJSONTyped(value?: KeynoteDtosResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keynote': KeynoteDTOToJSON(value['keynote']),
        'createKeynote': CreateKeynoteDTOToJSON(value['createKeynote']),
        'keynoteUser': KeynoteUserDTOToJSON(value['keynoteUser']),
    };
}

