/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KeynoteDTO } from './KeynoteDTO';
import {
    KeynoteDTOFromJSON,
    KeynoteDTOFromJSONTyped,
    KeynoteDTOToJSON,
    KeynoteDTOToJSONTyped,
} from './KeynoteDTO';

/**
 * 
 * @export
 * @interface KeynoteUserDTO
 */
export interface KeynoteUserDTO {
    /**
     * 
     * @type {string}
     * @memberof KeynoteUserDTO
     */
    id?: string | null;
    /**
     * 
     * @type {Array<KeynoteDTO>}
     * @memberof KeynoteUserDTO
     */
    keynotes?: Array<KeynoteDTO> | null;
}

/**
 * Check if a given object implements the KeynoteUserDTO interface.
 */
export function instanceOfKeynoteUserDTO(value: object): value is KeynoteUserDTO {
    return true;
}

export function KeynoteUserDTOFromJSON(json: any): KeynoteUserDTO {
    return KeynoteUserDTOFromJSONTyped(json, false);
}

export function KeynoteUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeynoteUserDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'keynotes': json['keynotes'] == null ? undefined : ((json['keynotes'] as Array<any>).map(KeynoteDTOFromJSON)),
    };
}

export function KeynoteUserDTOToJSON(json: any): KeynoteUserDTO {
    return KeynoteUserDTOToJSONTyped(json, false);
}

export function KeynoteUserDTOToJSONTyped(value?: KeynoteUserDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'keynotes': value['keynotes'] == null ? undefined : ((value['keynotes'] as Array<any>).map(KeynoteDTOToJSON)),
    };
}

