/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { KeynoteDTO } from "./KeynoteDTO";
import { KeynoteDTOFromJSON, KeynoteDTOFromJSONTyped, KeynoteDTOToJSON, KeynoteDTOToJSONTyped } from "./KeynoteDTO";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface KeynoteDTOResponseWrapper
 */
export interface KeynoteDTOResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof KeynoteDTOResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof KeynoteDTOResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {KeynoteDTO}
   * @memberof KeynoteDTOResponseWrapper
   */
  response?: KeynoteDTO;
}

/**
 * Check if a given object implements the KeynoteDTOResponseWrapper interface.
 */
export function instanceOfKeynoteDTOResponseWrapper(value: object): value is KeynoteDTOResponseWrapper {
  return true;
}

export function KeynoteDTOResponseWrapperFromJSON(json: any): KeynoteDTOResponseWrapper {
  return KeynoteDTOResponseWrapperFromJSONTyped(json, false);
}

export function KeynoteDTOResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeynoteDTOResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : KeynoteDTOFromJSON(json["response"]),
  };
}

export function KeynoteDTOResponseWrapperToJSON(json: any): KeynoteDTOResponseWrapper {
  return KeynoteDTOResponseWrapperToJSONTyped(json, false);
}

export function KeynoteDTOResponseWrapperToJSONTyped(value?: KeynoteDTOResponseWrapper | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: KeynoteDTOToJSON(value["response"]),
  };
}
