/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WrResponseStatus } from './WrResponseStatus';
import {
    WrResponseStatusFromJSON,
    WrResponseStatusFromJSONTyped,
    WrResponseStatusToJSON,
    WrResponseStatusToJSONTyped,
} from './WrResponseStatus';
import type { KeynoteUserDTO } from './KeynoteUserDTO';
import {
    KeynoteUserDTOFromJSON,
    KeynoteUserDTOFromJSONTyped,
    KeynoteUserDTOToJSON,
    KeynoteUserDTOToJSONTyped,
} from './KeynoteUserDTO';
import type { AuthFailureReasons } from './AuthFailureReasons';
import {
    AuthFailureReasonsFromJSON,
    AuthFailureReasonsFromJSONTyped,
    AuthFailureReasonsToJSON,
    AuthFailureReasonsToJSONTyped,
} from './AuthFailureReasons';

/**
 * 
 * @export
 * @interface KeynoteUserDTOResponseWrapper
 */
export interface KeynoteUserDTOResponseWrapper {
    /**
     * 
     * @type {WrResponseStatus}
     * @memberof KeynoteUserDTOResponseWrapper
     */
    status?: WrResponseStatus;
    /**
     * 
     * @type {Array<AuthFailureReasons>}
     * @memberof KeynoteUserDTOResponseWrapper
     */
    authenticationFailureReasons?: Array<AuthFailureReasons> | null;
    /**
     * 
     * @type {KeynoteUserDTO}
     * @memberof KeynoteUserDTOResponseWrapper
     */
    response?: KeynoteUserDTO;
}



/**
 * Check if a given object implements the KeynoteUserDTOResponseWrapper interface.
 */
export function instanceOfKeynoteUserDTOResponseWrapper(value: object): value is KeynoteUserDTOResponseWrapper {
    return true;
}

export function KeynoteUserDTOResponseWrapperFromJSON(json: any): KeynoteUserDTOResponseWrapper {
    return KeynoteUserDTOResponseWrapperFromJSONTyped(json, false);
}

export function KeynoteUserDTOResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeynoteUserDTOResponseWrapper {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : WrResponseStatusFromJSON(json['status']),
        'authenticationFailureReasons': json['authenticationFailureReasons'] == null ? undefined : ((json['authenticationFailureReasons'] as Array<any>).map(AuthFailureReasonsFromJSON)),
        'response': json['response'] == null ? undefined : KeynoteUserDTOFromJSON(json['response']),
    };
}

export function KeynoteUserDTOResponseWrapperToJSON(json: any): KeynoteUserDTOResponseWrapper {
    return KeynoteUserDTOResponseWrapperToJSONTyped(json, false);
}

export function KeynoteUserDTOResponseWrapperToJSONTyped(value?: KeynoteUserDTOResponseWrapper | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': WrResponseStatusToJSON(value['status']),
        'authenticationFailureReasons': value['authenticationFailureReasons'] == null ? undefined : ((value['authenticationFailureReasons'] as Array<any>).map(AuthFailureReasonsToJSON)),
        'response': KeynoteUserDTOToJSON(value['response']),
    };
}

