/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WrResponseStatus } from './WrResponseStatus';
import {
    WrResponseStatusFromJSON,
    WrResponseStatusFromJSONTyped,
    WrResponseStatusToJSON,
    WrResponseStatusToJSONTyped,
} from './WrResponseStatus';
import type { KeynoteDtosResponse } from './KeynoteDtosResponse';
import {
    KeynoteDtosResponseFromJSON,
    KeynoteDtosResponseFromJSONTyped,
    KeynoteDtosResponseToJSON,
    KeynoteDtosResponseToJSONTyped,
} from './KeynoteDtosResponse';
import type { AuthFailureReasons } from './AuthFailureReasons';
import {
    AuthFailureReasonsFromJSON,
    AuthFailureReasonsFromJSONTyped,
    AuthFailureReasonsToJSON,
    AuthFailureReasonsToJSONTyped,
} from './AuthFailureReasons';

/**
 * 
 * @export
 * @interface KeynoteDtosResponseResponseWrapper
 */
export interface KeynoteDtosResponseResponseWrapper {
    /**
     * 
     * @type {WrResponseStatus}
     * @memberof KeynoteDtosResponseResponseWrapper
     */
    status?: WrResponseStatus;
    /**
     * 
     * @type {Array<AuthFailureReasons>}
     * @memberof KeynoteDtosResponseResponseWrapper
     */
    authenticationFailureReasons?: Array<AuthFailureReasons> | null;
    /**
     * 
     * @type {KeynoteDtosResponse}
     * @memberof KeynoteDtosResponseResponseWrapper
     */
    response?: KeynoteDtosResponse;
}



/**
 * Check if a given object implements the KeynoteDtosResponseResponseWrapper interface.
 */
export function instanceOfKeynoteDtosResponseResponseWrapper(value: object): value is KeynoteDtosResponseResponseWrapper {
    return true;
}

export function KeynoteDtosResponseResponseWrapperFromJSON(json: any): KeynoteDtosResponseResponseWrapper {
    return KeynoteDtosResponseResponseWrapperFromJSONTyped(json, false);
}

export function KeynoteDtosResponseResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeynoteDtosResponseResponseWrapper {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : WrResponseStatusFromJSON(json['status']),
        'authenticationFailureReasons': json['authenticationFailureReasons'] == null ? undefined : ((json['authenticationFailureReasons'] as Array<any>).map(AuthFailureReasonsFromJSON)),
        'response': json['response'] == null ? undefined : KeynoteDtosResponseFromJSON(json['response']),
    };
}

export function KeynoteDtosResponseResponseWrapperToJSON(json: any): KeynoteDtosResponseResponseWrapper {
    return KeynoteDtosResponseResponseWrapperToJSONTyped(json, false);
}

export function KeynoteDtosResponseResponseWrapperToJSONTyped(value?: KeynoteDtosResponseResponseWrapper | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': WrResponseStatusToJSON(value['status']),
        'authenticationFailureReasons': value['authenticationFailureReasons'] == null ? undefined : ((value['authenticationFailureReasons'] as Array<any>).map(AuthFailureReasonsToJSON)),
        'response': KeynoteDtosResponseToJSON(value['response']),
    };
}

