/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { ListDtosResponse } from "./ListDtosResponse";
import { ListDtosResponseFromJSON, ListDtosResponseFromJSONTyped, ListDtosResponseToJSON, ListDtosResponseToJSONTyped } from "./ListDtosResponse";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface ListDtosResponseResponseWrapper
 */
export interface ListDtosResponseResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof ListDtosResponseResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof ListDtosResponseResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {ListDtosResponse}
   * @memberof ListDtosResponseResponseWrapper
   */
  response?: ListDtosResponse;
}

/**
 * Check if a given object implements the ListDtosResponseResponseWrapper interface.
 */
export function instanceOfListDtosResponseResponseWrapper(value: object): value is ListDtosResponseResponseWrapper {
  return true;
}

export function ListDtosResponseResponseWrapperFromJSON(json: any): ListDtosResponseResponseWrapper {
  return ListDtosResponseResponseWrapperFromJSONTyped(json, false);
}

export function ListDtosResponseResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDtosResponseResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : ListDtosResponseFromJSON(json["response"]),
  };
}

export function ListDtosResponseResponseWrapperToJSON(json: any): ListDtosResponseResponseWrapper {
  return ListDtosResponseResponseWrapperToJSONTyped(json, false);
}

export function ListDtosResponseResponseWrapperToJSONTyped(
  value?: ListDtosResponseResponseWrapper | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: ListDtosResponseToJSON(value["response"]),
  };
}
