/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TRScreenDTO } from './TRScreenDTO';
import {
    TRScreenDTOFromJSON,
    TRScreenDTOFromJSONTyped,
    TRScreenDTOToJSON,
    TRScreenDTOToJSONTyped,
} from './TRScreenDTO';
import type { TRSpectatorDTO } from './TRSpectatorDTO';
import {
    TRSpectatorDTOFromJSON,
    TRSpectatorDTOFromJSONTyped,
    TRSpectatorDTOToJSON,
    TRSpectatorDTOToJSONTyped,
} from './TRSpectatorDTO';
import type { KeynoteDTO } from './KeynoteDTO';
import {
    KeynoteDTOFromJSON,
    KeynoteDTOFromJSONTyped,
    KeynoteDTOToJSON,
    KeynoteDTOToJSONTyped,
} from './KeynoteDTO';
import type { TRPresentorDTO } from './TRPresentorDTO';
import {
    TRPresentorDTOFromJSON,
    TRPresentorDTOFromJSONTyped,
    TRPresentorDTOToJSON,
    TRPresentorDTOToJSONTyped,
} from './TRPresentorDTO';
import type { TRRoomDTO } from './TRRoomDTO';
import {
    TRRoomDTOFromJSON,
    TRRoomDTOFromJSONTyped,
    TRRoomDTOToJSON,
    TRRoomDTOToJSONTyped,
} from './TRRoomDTO';

/**
 * 
 * @export
 * @interface ListDtosResponse
 */
export interface ListDtosResponse {
    /**
     * 
     * @type {Array<TRRoomDTO>}
     * @memberof ListDtosResponse
     */
    roomList?: Array<TRRoomDTO> | null;
    /**
     * 
     * @type {Array<TRPresentorDTO>}
     * @memberof ListDtosResponse
     */
    presentorList?: Array<TRPresentorDTO> | null;
    /**
     * 
     * @type {Array<TRScreenDTO>}
     * @memberof ListDtosResponse
     */
    screenList?: Array<TRScreenDTO> | null;
    /**
     * 
     * @type {Array<TRSpectatorDTO>}
     * @memberof ListDtosResponse
     */
    spectatorList?: Array<TRSpectatorDTO> | null;
    /**
     * 
     * @type {Array<KeynoteDTO>}
     * @memberof ListDtosResponse
     */
    keynoteList?: Array<KeynoteDTO> | null;
}

/**
 * Check if a given object implements the ListDtosResponse interface.
 */
export function instanceOfListDtosResponse(value: object): value is ListDtosResponse {
    return true;
}

export function ListDtosResponseFromJSON(json: any): ListDtosResponse {
    return ListDtosResponseFromJSONTyped(json, false);
}

export function ListDtosResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDtosResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'roomList': json['roomList'] == null ? undefined : ((json['roomList'] as Array<any>).map(TRRoomDTOFromJSON)),
        'presentorList': json['presentorList'] == null ? undefined : ((json['presentorList'] as Array<any>).map(TRPresentorDTOFromJSON)),
        'screenList': json['screenList'] == null ? undefined : ((json['screenList'] as Array<any>).map(TRScreenDTOFromJSON)),
        'spectatorList': json['spectatorList'] == null ? undefined : ((json['spectatorList'] as Array<any>).map(TRSpectatorDTOFromJSON)),
        'keynoteList': json['keynoteList'] == null ? undefined : ((json['keynoteList'] as Array<any>).map(KeynoteDTOFromJSON)),
    };
}

export function ListDtosResponseToJSON(json: any): ListDtosResponse {
    return ListDtosResponseToJSONTyped(json, false);
}

export function ListDtosResponseToJSONTyped(value?: ListDtosResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'roomList': value['roomList'] == null ? undefined : ((value['roomList'] as Array<any>).map(TRRoomDTOToJSON)),
        'presentorList': value['presentorList'] == null ? undefined : ((value['presentorList'] as Array<any>).map(TRPresentorDTOToJSON)),
        'screenList': value['screenList'] == null ? undefined : ((value['screenList'] as Array<any>).map(TRScreenDTOToJSON)),
        'spectatorList': value['spectatorList'] == null ? undefined : ((value['spectatorList'] as Array<any>).map(TRSpectatorDTOToJSON)),
        'keynoteList': value['keynoteList'] == null ? undefined : ((value['keynoteList'] as Array<any>).map(KeynoteDTOToJSON)),
    };
}

