/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PermissionBasicDTO
 */
export interface PermissionBasicDTO {
  /**
   *
   * @type {Date}
   * @memberof PermissionBasicDTO
   */
  createdAt?: Date | null;
  /**
   *
   * @type {string}
   * @memberof PermissionBasicDTO
   */
  id?: string | null;
  /**
   *
   * @type {string}
   * @memberof PermissionBasicDTO
   */
  key?: string | null;
  /**
   *
   * @type {string}
   * @memberof PermissionBasicDTO
   */
  name?: string | null;
  /**
   *
   * @type {string}
   * @memberof PermissionBasicDTO
   */
  serviceId?: string | null;
}

/**
 * Check if a given object implements the PermissionBasicDTO interface.
 */
export function instanceOfPermissionBasicDTO(value: object): value is PermissionBasicDTO {
  return true;
}

export function PermissionBasicDTOFromJSON(json: any): PermissionBasicDTO {
  return PermissionBasicDTOFromJSONTyped(json, false);
}

export function PermissionBasicDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionBasicDTO {
  if (json == null) {
    return json;
  }
  return {
    createdAt: json["createdAt"] == null ? undefined : new Date(json["createdAt"]),
    id: json["id"] == null ? undefined : json["id"],
    key: json["key"] == null ? undefined : json["key"],
    name: json["name"] == null ? undefined : json["name"],
    serviceId: json["serviceId"] == null ? undefined : json["serviceId"],
  };
}

export function PermissionBasicDTOToJSON(json: any): PermissionBasicDTO {
  return PermissionBasicDTOToJSONTyped(json, false);
}

export function PermissionBasicDTOToJSONTyped(value?: PermissionBasicDTO | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    createdAt: value["createdAt"] === null ? null : (value["createdAt"] as any)?.toISOString(),
    id: value["id"],
    key: value["key"],
    name: value["name"],
    serviceId: value["serviceId"],
  };
}
