/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WrResponseStatus } from './WrResponseStatus';
import {
    WrResponseStatusFromJSON,
    WrResponseStatusFromJSONTyped,
    WrResponseStatusToJSON,
    WrResponseStatusToJSONTyped,
} from './WrResponseStatus';
import type { RoomDtosResponse } from './RoomDtosResponse';
import {
    RoomDtosResponseFromJSON,
    RoomDtosResponseFromJSONTyped,
    RoomDtosResponseToJSON,
    RoomDtosResponseToJSONTyped,
} from './RoomDtosResponse';
import type { AuthFailureReasons } from './AuthFailureReasons';
import {
    AuthFailureReasonsFromJSON,
    AuthFailureReasonsFromJSONTyped,
    AuthFailureReasonsToJSON,
    AuthFailureReasonsToJSONTyped,
} from './AuthFailureReasons';

/**
 * 
 * @export
 * @interface RoomDtosResponseResponseWrapper
 */
export interface RoomDtosResponseResponseWrapper {
    /**
     * 
     * @type {WrResponseStatus}
     * @memberof RoomDtosResponseResponseWrapper
     */
    status?: WrResponseStatus;
    /**
     * 
     * @type {Array<AuthFailureReasons>}
     * @memberof RoomDtosResponseResponseWrapper
     */
    authenticationFailureReasons?: Array<AuthFailureReasons> | null;
    /**
     * 
     * @type {RoomDtosResponse}
     * @memberof RoomDtosResponseResponseWrapper
     */
    response?: RoomDtosResponse;
}



/**
 * Check if a given object implements the RoomDtosResponseResponseWrapper interface.
 */
export function instanceOfRoomDtosResponseResponseWrapper(value: object): value is RoomDtosResponseResponseWrapper {
    return true;
}

export function RoomDtosResponseResponseWrapperFromJSON(json: any): RoomDtosResponseResponseWrapper {
    return RoomDtosResponseResponseWrapperFromJSONTyped(json, false);
}

export function RoomDtosResponseResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomDtosResponseResponseWrapper {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : WrResponseStatusFromJSON(json['status']),
        'authenticationFailureReasons': json['authenticationFailureReasons'] == null ? undefined : ((json['authenticationFailureReasons'] as Array<any>).map(AuthFailureReasonsFromJSON)),
        'response': json['response'] == null ? undefined : RoomDtosResponseFromJSON(json['response']),
    };
}

export function RoomDtosResponseResponseWrapperToJSON(json: any): RoomDtosResponseResponseWrapper {
    return RoomDtosResponseResponseWrapperToJSONTyped(json, false);
}

export function RoomDtosResponseResponseWrapperToJSONTyped(value?: RoomDtosResponseResponseWrapper | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': WrResponseStatusToJSON(value['status']),
        'authenticationFailureReasons': value['authenticationFailureReasons'] == null ? undefined : ((value['authenticationFailureReasons'] as Array<any>).map(AuthFailureReasonsToJSON)),
        'response': RoomDtosResponseToJSON(value['response']),
    };
}

