/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionIdentifiersResponse
 */
export interface SessionIdentifiersResponse {
    /**
     * 
     * @type {string}
     * @memberof SessionIdentifiersResponse
     */
    screenIdentifier?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SessionIdentifiersResponse
     */
    spectatorIdentifier?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SessionIdentifiersResponse
     */
    presentorSessionId?: string | null;
}

/**
 * Check if a given object implements the SessionIdentifiersResponse interface.
 */
export function instanceOfSessionIdentifiersResponse(value: object): value is SessionIdentifiersResponse {
    return true;
}

export function SessionIdentifiersResponseFromJSON(json: any): SessionIdentifiersResponse {
    return SessionIdentifiersResponseFromJSONTyped(json, false);
}

export function SessionIdentifiersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionIdentifiersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'screenIdentifier': json['screenIdentifier'] == null ? undefined : json['screenIdentifier'],
        'spectatorIdentifier': json['spectatorIdentifier'] == null ? undefined : json['spectatorIdentifier'],
        'presentorSessionId': json['presentorSessionId'] == null ? undefined : json['presentorSessionId'],
    };
}

export function SessionIdentifiersResponseToJSON(json: any): SessionIdentifiersResponse {
    return SessionIdentifiersResponseToJSONTyped(json, false);
}

export function SessionIdentifiersResponseToJSONTyped(value?: SessionIdentifiersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'screenIdentifier': value['screenIdentifier'],
        'spectatorIdentifier': value['spectatorIdentifier'],
        'presentorSessionId': value['presentorSessionId'],
    };
}

