/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { SessionIdentifiersResponse } from "./SessionIdentifiersResponse";
import {
  SessionIdentifiersResponseFromJSON,
  SessionIdentifiersResponseFromJSONTyped,
  SessionIdentifiersResponseToJSON,
  SessionIdentifiersResponseToJSONTyped,
} from "./SessionIdentifiersResponse";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface SessionIdentifiersResponseResponseWrapper
 */
export interface SessionIdentifiersResponseResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof SessionIdentifiersResponseResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof SessionIdentifiersResponseResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {SessionIdentifiersResponse}
   * @memberof SessionIdentifiersResponseResponseWrapper
   */
  response?: SessionIdentifiersResponse;
}

/**
 * Check if a given object implements the SessionIdentifiersResponseResponseWrapper interface.
 */
export function instanceOfSessionIdentifiersResponseResponseWrapper(value: object): value is SessionIdentifiersResponseResponseWrapper {
  return true;
}

export function SessionIdentifiersResponseResponseWrapperFromJSON(json: any): SessionIdentifiersResponseResponseWrapper {
  return SessionIdentifiersResponseResponseWrapperFromJSONTyped(json, false);
}

export function SessionIdentifiersResponseResponseWrapperFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SessionIdentifiersResponseResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : SessionIdentifiersResponseFromJSON(json["response"]),
  };
}

export function SessionIdentifiersResponseResponseWrapperToJSON(json: any): SessionIdentifiersResponseResponseWrapper {
  return SessionIdentifiersResponseResponseWrapperToJSONTyped(json, false);
}

export function SessionIdentifiersResponseResponseWrapperToJSONTyped(
  value?: SessionIdentifiersResponseResponseWrapper | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: SessionIdentifiersResponseToJSON(value["response"]),
  };
}
