/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceBasicDTO } from './ServiceBasicDTO';
import {
    ServiceBasicDTOFromJSON,
    ServiceBasicDTOFromJSONTyped,
    ServiceBasicDTOToJSON,
    ServiceBasicDTOToJSONTyped,
} from './ServiceBasicDTO';

/**
 * 
 * @export
 * @interface SessionDTO
 */
export interface SessionDTO {
    /**
     * 
     * @type {string}
     * @memberof SessionDTO
     */
    browser?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof SessionDTO
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof SessionDTO
     */
    device?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof SessionDTO
     */
    expiresAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof SessionDTO
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SessionDTO
     */
    ipAddress?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SessionDTO
     */
    is2FAConfirmed?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof SessionDTO
     */
    os?: string | null;
    /**
     * 
     * @type {ServiceBasicDTO}
     * @memberof SessionDTO
     */
    service?: ServiceBasicDTO;
    /**
     * 
     * @type {string}
     * @memberof SessionDTO
     */
    serviceId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SessionDTO
     */
    userId?: string | null;
}

/**
 * Check if a given object implements the SessionDTO interface.
 */
export function instanceOfSessionDTO(value: object): value is SessionDTO {
    return true;
}

export function SessionDTOFromJSON(json: any): SessionDTO {
    return SessionDTOFromJSONTyped(json, false);
}

export function SessionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'browser': json['browser'] == null ? undefined : json['browser'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'device': json['device'] == null ? undefined : json['device'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'ipAddress': json['ipAddress'] == null ? undefined : json['ipAddress'],
        'is2FAConfirmed': json['is2FAConfirmed'] == null ? undefined : json['is2FAConfirmed'],
        'os': json['os'] == null ? undefined : json['os'],
        'service': json['service'] == null ? undefined : ServiceBasicDTOFromJSON(json['service']),
        'serviceId': json['serviceId'] == null ? undefined : json['serviceId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function SessionDTOToJSON(json: any): SessionDTO {
    return SessionDTOToJSONTyped(json, false);
}

export function SessionDTOToJSONTyped(value?: SessionDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'browser': value['browser'],
        'createdAt': value['createdAt'] === null ? null : ((value['createdAt'] as any)?.toISOString()),
        'device': value['device'],
        'expiresAt': value['expiresAt'] === null ? null : ((value['expiresAt'] as any)?.toISOString()),
        'id': value['id'],
        'ipAddress': value['ipAddress'],
        'is2FAConfirmed': value['is2FAConfirmed'],
        'os': value['os'],
        'service': ServiceBasicDTOToJSON(value['service']),
        'serviceId': value['serviceId'],
        'userId': value['userId'],
    };
}

