/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TRBaseEntityDTO
 */
export interface TRBaseEntityDTO {
    /**
     * 
     * @type {string}
     * @memberof TRBaseEntityDTO
     */
    identifier?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TRBaseEntityDTO
     */
    roomCode?: string | null;
}

/**
 * Check if a given object implements the TRBaseEntityDTO interface.
 */
export function instanceOfTRBaseEntityDTO(value: object): value is TRBaseEntityDTO {
    return true;
}

export function TRBaseEntityDTOFromJSON(json: any): TRBaseEntityDTO {
    return TRBaseEntityDTOFromJSONTyped(json, false);
}

export function TRBaseEntityDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TRBaseEntityDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'identifier': json['identifier'] == null ? undefined : json['identifier'],
        'roomCode': json['roomCode'] == null ? undefined : json['roomCode'],
    };
}

export function TRBaseEntityDTOToJSON(json: any): TRBaseEntityDTO {
    return TRBaseEntityDTOToJSONTyped(json, false);
}

export function TRBaseEntityDTOToJSONTyped(value?: TRBaseEntityDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identifier': value['identifier'],
        'roomCode': value['roomCode'],
    };
}

