/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TRPresentorDTO
 */
export interface TRPresentorDTO {
  /**
   *
   * @type {string}
   * @memberof TRPresentorDTO
   */
  identifier?: string | null;
  /**
   *
   * @type {string}
   * @memberof TRPresentorDTO
   */
  roomCode?: string | null;
  /**
   *
   * @type {string}
   * @memberof TRPresentorDTO
   */
  name?: string | null;
}

/**
 * Check if a given object implements the TRPresentorDTO interface.
 */
export function instanceOfTRPresentorDTO(value: object): value is TRPresentorDTO {
  return true;
}

export function TRPresentorDTOFromJSON(json: any): TRPresentorDTO {
  return TRPresentorDTOFromJSONTyped(json, false);
}

export function TRPresentorDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TRPresentorDTO {
  if (json == null) {
    return json;
  }
  return {
    identifier: json["identifier"] == null ? undefined : json["identifier"],
    roomCode: json["roomCode"] == null ? undefined : json["roomCode"],
    name: json["name"] == null ? undefined : json["name"],
  };
}

export function TRPresentorDTOToJSON(json: any): TRPresentorDTO {
  return TRPresentorDTOToJSONTyped(json, false);
}

export function TRPresentorDTOToJSONTyped(value?: TRPresentorDTO | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    identifier: value["identifier"],
    roomCode: value["roomCode"],
    name: value["name"],
  };
}
