/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TRScreenDTO
 */
export interface TRScreenDTO {
    /**
     * 
     * @type {string}
     * @memberof TRScreenDTO
     */
    identifier?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TRScreenDTO
     */
    roomCode?: string | null;
}

/**
 * Check if a given object implements the TRScreenDTO interface.
 */
export function instanceOfTRScreenDTO(value: object): value is TRScreenDTO {
    return true;
}

export function TRScreenDTOFromJSON(json: any): TRScreenDTO {
    return TRScreenDTOFromJSONTyped(json, false);
}

export function TRScreenDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TRScreenDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'identifier': json['identifier'] == null ? undefined : json['identifier'],
        'roomCode': json['roomCode'] == null ? undefined : json['roomCode'],
    };
}

export function TRScreenDTOToJSON(json: any): TRScreenDTO {
    return TRScreenDTOToJSONTyped(json, false);
}

export function TRScreenDTOToJSONTyped(value?: TRScreenDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identifier': value['identifier'],
        'roomCode': value['roomCode'],
    };
}

