/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TRSpectatorDTO
 */
export interface TRSpectatorDTO {
  /**
   *
   * @type {string}
   * @memberof TRSpectatorDTO
   */
  identifier?: string | null;
  /**
   *
   * @type {string}
   * @memberof TRSpectatorDTO
   */
  roomCode?: string | null;
  /**
   *
   * @type {string}
   * @memberof TRSpectatorDTO
   */
  name?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof TRSpectatorDTO
   */
  isHandRaised?: boolean;
}

/**
 * Check if a given object implements the TRSpectatorDTO interface.
 */
export function instanceOfTRSpectatorDTO(value: object): value is TRSpectatorDTO {
  return true;
}

export function TRSpectatorDTOFromJSON(json: any): TRSpectatorDTO {
  return TRSpectatorDTOFromJSONTyped(json, false);
}

export function TRSpectatorDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TRSpectatorDTO {
  if (json == null) {
    return json;
  }
  return {
    identifier: json["identifier"] == null ? undefined : json["identifier"],
    roomCode: json["roomCode"] == null ? undefined : json["roomCode"],
    name: json["name"] == null ? undefined : json["name"],
    isHandRaised: json["isHandRaised"] == null ? undefined : json["isHandRaised"],
  };
}

export function TRSpectatorDTOToJSON(json: any): TRSpectatorDTO {
  return TRSpectatorDTOToJSONTyped(json, false);
}

export function TRSpectatorDTOToJSONTyped(value?: TRSpectatorDTO | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    identifier: value["identifier"],
    roomCode: value["roomCode"],
    name: value["name"],
    isHandRaised: value["isHandRaised"],
  };
}
