/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ServicePermissionOnUserUpdateDTOInner } from "./ServicePermissionOnUserUpdateDTOInner";
import {
  ServicePermissionOnUserUpdateDTOInnerFromJSON,
  ServicePermissionOnUserUpdateDTOInnerFromJSONTyped,
  ServicePermissionOnUserUpdateDTOInnerToJSON,
  ServicePermissionOnUserUpdateDTOInnerToJSONTyped,
} from "./ServicePermissionOnUserUpdateDTOInner";

/**
 *
 * @export
 * @interface ServiceUpdateUserPermissionsDTO
 */
export interface ServiceUpdateUserPermissionsDTO {
  /**
   *
   * @type {string}
   * @memberof ServiceUpdateUserPermissionsDTO
   */
  userId?: string | null;
  /**
   *
   * @type {string}
   * @memberof ServiceUpdateUserPermissionsDTO
   */
  sessionId?: string | null;
  /**
   *
   * @type {Array<ServicePermissionOnUserUpdateDTOInner>}
   * @memberof ServiceUpdateUserPermissionsDTO
   */
  permissions?: Array<ServicePermissionOnUserUpdateDTOInner> | null;
}

/**
 * Check if a given object implements the ServiceUpdateUserPermissionsDTO interface.
 */
export function instanceOfServiceUpdateUserPermissionsDTO(value: object): value is ServiceUpdateUserPermissionsDTO {
  return true;
}

export function ServiceUpdateUserPermissionsDTOFromJSON(json: any): ServiceUpdateUserPermissionsDTO {
  return ServiceUpdateUserPermissionsDTOFromJSONTyped(json, false);
}

export function ServiceUpdateUserPermissionsDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceUpdateUserPermissionsDTO {
  if (json == null) {
    return json;
  }
  return {
    userId: json["userId"] == null ? undefined : json["userId"],
    sessionId: json["sessionId"] == null ? undefined : json["sessionId"],
    permissions: json["permissions"] == null ? undefined : (json["permissions"] as Array<any>).map(ServicePermissionOnUserUpdateDTOInnerFromJSON),
  };
}

export function ServiceUpdateUserPermissionsDTOToJSON(json: any): ServiceUpdateUserPermissionsDTO {
  return ServiceUpdateUserPermissionsDTOToJSONTyped(json, false);
}

export function ServiceUpdateUserPermissionsDTOToJSONTyped(
  value?: ServiceUpdateUserPermissionsDTO | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    userId: value["userId"],
    sessionId: value["sessionId"],
    permissions: value["permissions"] == null ? undefined : (value["permissions"] as Array<any>).map(ServicePermissionOnUserUpdateDTOInnerToJSON),
  };
}
