/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  EnumsResponse,
  EnumsResponseResponseWrapper,
  KeynoteDtosResponse,
  KeynoteDtosResponseResponseWrapper,
  ListDtosResponse,
  ListDtosResponseResponseWrapper,
  RoomDtosResponseResponseWrapper,
} from "../models/index";
import {
  EnumsResponseFromJSON,
  EnumsResponseToJSON,
  EnumsResponseResponseWrapperFromJSON,
  EnumsResponseResponseWrapperToJSON,
  KeynoteDtosResponseFromJSON,
  KeynoteDtosResponseToJSON,
  KeynoteDtosResponseResponseWrapperFromJSON,
  KeynoteDtosResponseResponseWrapperToJSON,
  ListDtosResponseFromJSON,
  ListDtosResponseToJSON,
  ListDtosResponseResponseWrapperFromJSON,
  ListDtosResponseResponseWrapperToJSON,
  RoomDtosResponseResponseWrapperFromJSON,
  RoomDtosResponseResponseWrapperToJSON,
} from "../models/index";

export interface ApiSwaggerDtoEnumsGetRequest {
  enumsResponse?: EnumsResponse;
}

export interface ApiSwaggerDtoKeynoteDtosGetRequest {
  keynoteDtosResponse?: KeynoteDtosResponse;
}

export interface ApiSwaggerDtoListDtosGetRequest {
  listDtosResponse?: ListDtosResponse;
}

/**
 *
 */
export class SwaggerDtoApi extends runtime.BaseAPI {
  /**
   */
  async apiSwaggerDtoEnumsGetRaw(
    requestParameters: ApiSwaggerDtoEnumsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EnumsResponseResponseWrapper>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/SwaggerDto/enums`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
        body: EnumsResponseToJSON(requestParameters["enumsResponse"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => EnumsResponseResponseWrapperFromJSON(jsonValue));
  }

  /**
   */
  async apiSwaggerDtoEnumsGet(
    requestParameters: ApiSwaggerDtoEnumsGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EnumsResponseResponseWrapper> {
    const response = await this.apiSwaggerDtoEnumsGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async apiSwaggerDtoKeynoteDtosGetRaw(
    requestParameters: ApiSwaggerDtoKeynoteDtosGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<KeynoteDtosResponseResponseWrapper>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/SwaggerDto/keynote-dtos`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
        body: KeynoteDtosResponseToJSON(requestParameters["keynoteDtosResponse"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => KeynoteDtosResponseResponseWrapperFromJSON(jsonValue));
  }

  /**
   */
  async apiSwaggerDtoKeynoteDtosGet(
    requestParameters: ApiSwaggerDtoKeynoteDtosGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<KeynoteDtosResponseResponseWrapper> {
    const response = await this.apiSwaggerDtoKeynoteDtosGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async apiSwaggerDtoListDtosGetRaw(
    requestParameters: ApiSwaggerDtoListDtosGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListDtosResponseResponseWrapper>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/SwaggerDto/list-dtos`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
        body: ListDtosResponseToJSON(requestParameters["listDtosResponse"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ListDtosResponseResponseWrapperFromJSON(jsonValue));
  }

  /**
   */
  async apiSwaggerDtoListDtosGet(
    requestParameters: ApiSwaggerDtoListDtosGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListDtosResponseResponseWrapper> {
    const response = await this.apiSwaggerDtoListDtosGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async apiSwaggerDtoRoomDtosGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RoomDtosResponseResponseWrapper>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/SwaggerDto/room-dtos`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => RoomDtosResponseResponseWrapperFromJSON(jsonValue));
  }

  /**
   */
  async apiSwaggerDtoRoomDtosGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoomDtosResponseResponseWrapper> {
    const response = await this.apiSwaggerDtoRoomDtosGetRaw(initOverrides);
    return await response.value();
  }
}
