/* tslint:disable */
/* eslint-disable */
/**
 * ketnote-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { KeynoteUserDTOResponseWrapper } from "../models/index";
import { KeynoteUserDTOResponseWrapperFromJSON, KeynoteUserDTOResponseWrapperToJSON } from "../models/index";

/**
 *
 */
export class UserApi extends runtime.BaseAPI {
  /**
   */
  async apiUserCurrentUserGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<KeynoteUserDTOResponseWrapper>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/User/currentUser`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => KeynoteUserDTOResponseWrapperFromJSON(jsonValue));
  }

  /**
   */
  async apiUserCurrentUserGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeynoteUserDTOResponseWrapper> {
    const response = await this.apiUserCurrentUserGetRaw(initOverrides);
    return await response.value();
  }
}
